export const FETCH_CURRENT_DATA_REQUEST = 'FETCH_CURRENT_DATA_REQUEST';
export const FETCH_CURRENT_DATA_SUCCESS = 'FETCH_CURRENT_DATA_SUCCESS';
export const FETCH_CURRENT_DATA_FAILURE = 'FETCH_CURRENT_DATA_FAILURE';

export const FETCH_DAILY_DATA_REQUEST = 'FETCH_DAILY_DATA_REQUEST';
export const FETCH_DAILY_DATA_SUCCESS = 'FETCH_DAILY_DATA_SUCCESS';
export const FETCH_DAILY_DATA_FAILURE = 'FETCH_DAILY_DATA_FAILURE';